routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index');
// Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('users', 'UserController');
Route::get('userban/{id}','UserController@userBanUnban');
Route::get('searchuser','UserController@searchuser');

Route::resource('visas', 'VisaController');
// Route::get('notify/{id}','VisaController@notify');
// Route::get('ban_unban/{id}','VisaController@ban_unban');

Route::resource('banners', 'BannerController');

Route::resource('queries', 'QueryController');

Route::resource('reports', 'ReportController');

Route::resource('pages', 'PagesController');
Route::get('pageban/{id}','PagesController@pageBanUnban');
Route::get('searchpage','PagesController@searchpage');

Route::resource('interests', 'InterestController');

Route::resource('languages', 'LanguageController');

Route::resource('advertisements', 'AdvertisementController');

Route::resource('leaderboards', 'LeaderboardController');

Route::resource('posts', 'PostController');

Route::resource('categories', 'CategoriesController');

resources/views/pages/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('pages.index') !!}">Pages</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Pages</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'pages.store']) !!}

                                   @include('pages.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('pages.index') !!}">Pages</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Pages</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($pages, ['route' => ['pages.update', $pages->id], 'method' => 'patch']) !!}

                              @include('pages.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/pages/fields.blade.php
<!-- Page Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('page_title', 'Page Title:') !!}
    {!! Form::text('page_title', null, ['class' => 'form-control','maxlength' => 100,'maxlength' => 100,'maxlength' => 100]) !!}
</div>

<!-- Languages Field -->
<div class="form-group col-sm-6">
    {!! Form::label('languages', 'Languages:') !!}
    {!! Form::text('languages', null, ['class' => 'form-control','maxlength' => 100,'maxlength' => 100,'maxlength' => 100]) !!}
</div>

<!-- Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('interests', 'Interests:') !!}
    {!! Form::text('interests', null, ['class' => 'form-control','maxlength' => 100,'maxlength' => 100,'maxlength' => 100]) !!}
</div>

<!-- Cover Photo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('media', 'Page Media:') !!}
    <input type="file" class="form-control" name="cover_photo"/>
</div>

<!-- User Id Field -->
<!-- <div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div> -->

<div class="form-group col-sm-6">
    <label for="title">Choose User:</label>
    <select id="user" name="user" class="form-control">
        <option value="" selected disabled>Select</option>
        @foreach($users as $key => $user)
        <option value="{{$key}}"> {{$user}}</option>
        @endforeach
    </select>
</div>

<!-- Status Field -->
<!-- <div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control']) !!}
</div> -->

<!-- Followers Count Field -->
<!-- <div class="form-group col-sm-6">
    {!! Form::label('followers_count', 'Followers Count:') !!}
    {!! Form::number('followers_count', null, ['class' => 'form-control']) !!}
</div> -->

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('pages.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Pages</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <!-- <i class="fa fa-align-justify"></i>
                             Pages -->
                             <div style="text-align: center;">
                                <form action="searchuser" method="get">
                                    <input type="search" style="height: 35px;" class="search" name="search" placeholder="Search..">
                                    <button type="submit" class="btn btn-success button">Search</button>
                                </form>
                                <a class="pull-right" href="{{ route('pages.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                            </div>
                         </div>
                         <div class="card-body">
                             @include('pages.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('pages.index') }}">Pages</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('pages.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('pages.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/pages/show_fields.blade.php
<!-- Page Title Field -->
<div class="form-group">
    {!! Form::label('page_title', 'Page Title:') !!}
    <p>{{ $pages->page_title }}</p>
</div>

<!-- Languages Field -->
<div class="form-group">
    {!! Form::label('languages', 'Languages:') !!}
    <p>{{ $pages->languages }}</p>
</div>

<!-- Category Field -->
<div class="form-group">
    {!! Form::label('interests', 'Interests:') !!}
    <p>{{ $pages->interests }}</p>
</div>

<!-- Cover Photo Field -->
<div class="form-group">
    {!! Form::label('cover_photo', 'Cover Photo:') !!}
    <p>{{ $pages->cover_photo }}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $pages->user_id }}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $pages->status }}</p>
</div>

<!-- Followers Count Field -->
<div class="form-group">
    {!! Form::label('followers_count', 'Followers Count:') !!}
    <p>{{ $pages->followers_count }}</p>
</div>

resources/views/pages/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="pages-table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th>Page Title</th>
               <!--  <th>Languages</th>
                <th>Interests</th> -->
                <th>Cover Photo</th>
                <th>User Id</th>
                <th>Status</th>
                <th>Followers Count</th>
                <th>Ban</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = ($pages->currentPage() - 1) * $pages->perPage() + 1; ?>
        @foreach($pages as $page)
            <tr>
                <td scope="row">{!! $i++ !!}</td>
                <td>{{ $page->page_title }}</td>
                <!-- <td>{{ $page->languages }}</td>
                <td>{{ $page->interests }}</td> -->
                <td><a href="{!! url('/pages_images/'. $page->cover_photo) !!}" target="_blank">
                    <img src="{!! url('/pages_images/'. $page->cover_photo) !!}" width="auto;" height="80"></a>
                </td>
                <td>{{ $page->user_id }}</td>
                <td>{{ $page->status }}</td>
                <td>{{ $page->followers_count }}</td>
                <td>
                @if($page->status == 3)
                <a href="{{ url('/pageban/' . $page->id) }}" class='btn btn-ghost-danger'>
                   <i class="fa fa-check-square" aria-hidden="true"></i></a>
                @endif
                @if($page->status == 1)
                <a href="{{ url('/pageban/' . $page->id) }}" class='btn btn-ghost-danger'>
                <i class="fa fa-ban"></i></a>
                @endif
            </td>
                <td>
                    {!! Form::open(['route' => ['pages.destroy', $page->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('pages.show', [$page->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('pages.edit', [$page->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="col-5">
            <div class="float-right">
                {!! $pages->render() !!}
            </div>
        </div>
</div>